const SELECT_CITY = `@city/SELECT_CITY`;
const STORE_CITIES = `@city/STORE_CITIES`;

const STORE_OFFERS = `@offers/STORE_OFFERS`;
const STORE_HOTEL_DATA = `@offers/STORE_HOTEL_DATA`;
const UPDATE_OFFER = `@offers/UPDATE_OFFER`;

const CHANGE_SORT = `@sort/CHANGE_SORT`;

const CHANGE_AUTH_STATUS = `@auth/CHANGE_AUTH_STATUS`;
const STORE_USER_DATA = `@auth/STORE_USER_DATA`;
const REDIRECT_TO_ROUTE = `@auth/REDIRECT_TO_ROUTE`;

const APPEND_NOTIFICATION = `@notification/APPEND_NOTIFICATION`;
const REMOVE_NOTIFICATION = `@notification/REMOVE_NOTIFICATION`;

const STORE_COMMENTS = `@comments/STORE_COMMENTS`;

export {
  SELECT_CITY,
  STORE_CITIES,
  STORE_OFFERS,
  CHANGE_SORT,
  STORE_HOTEL_DATA,
  UPDATE_OFFER,
  CHANGE_AUTH_STATUS,
  STORE_USER_DATA,
  APPEND_NOTIFICATION,
  REMOVE_NOTIFICATION,
  STORE_COMMENTS,
  REDIRECT_TO_ROUTE,
};
