const SELECT_CITY = `@city/SELECT_CITY`;
const STORE_CITIES = `@city/STORE_CITIES`;

const STORE_OFFERS = `@favorite/STORE_OFFERS`;
const STORE_HOTEL_DATA = `@favorite/STORE_HOTEL_DATA`;

const CHANGE_SORT = `@sort/CHANGE_SORT`;

const CHANGE_AUTH_STATUS = `@auth/CHANGE_AUTH_STATUS`;

export {
  SELECT_CITY,
  STORE_CITIES,
  STORE_OFFERS,
  CHANGE_SORT,
  STORE_HOTEL_DATA,
  CHANGE_AUTH_STATUS,
};
