const STORE_OFFERS = `@offers/STORE_OFFERS`;
const STORE_HOTEL_DATA = `@offers/STORE_HOTEL_DATA`;
const UPDATE_OFFER = `@offers/UPDATE_OFFER`;
const CHANGE_SORT = `@offers/CHANGE_SORT`;

export {
  STORE_OFFERS,
  STORE_HOTEL_DATA,
  UPDATE_OFFER,
  CHANGE_SORT,
};
